# Replace the contents of `codechat_config.yaml` with this file to edit Precalculus
source_path: precalculus/source
output_path: output/precal-web-insructor
args: "{sys_executable} -m pretext build precal-web-insructor --xmlid {xml_id} --no-knowls"
project_type: PreTeXt
