# Replace the contents of `codechat_config.yaml` with this file to edit Calculus
output_path: output/cal-web-custom
args: "{sys_executable} -m pretext build cal-web-custom --xmlid {xml_id} --no-knowls"
project_type: PreTeXt
