# Replace the contents of `codechat_config.yaml` with this file to edit Linear Algebra
output_path: output/la-web-instructor
args: "{sys_executable} -m pretext build la-web-instructor --xmlid {xml_id} --no-knowls"
project_type: PreTeXt
